language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

env: SYMFONY_VERSION=2.3.*

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer install --prefer-source

script: bin/phpunit --coverage-clover clover.xml

after_script: bin/coveralls -v

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.2.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*@dev
    allow_failures:
        - php: 7.0
        - php: hhvm
        - env: SYMFONY_VERSION=2.8.*@dev

notifications:
    email: geloen.eric@gmail.com
