language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env: SYMFONY_VERSION=2.3.*

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - if [[ "$TRAVIS_PHP_VERSION" = 5.3* ]]; then composer remove guzzlehttp/guzzle --dev --no-update; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "5.3.3" ]]; then composer remove zendframework/zendframework --dev --no-update; fi
    - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer install --prefer-source

script: bin/phpunit --coverage-clover clover.xml

after_script: bin/coveralls -v

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.1.*
        - php: 5.6
          env: SYMFONY_VERSION=2.2.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*@dev
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*@dev
    allow_failures:
        - php: hhvm-nightly
        - env: SYMFONY_VERSION=2.6.*@dev
        - env: SYMFONY_VERSION=2.7.*@dev

notifications:
    email: geloen.eric@gmail.com
